### ISSUE TITLE
Error message for these lines in markov_msm

### ISSUE THREAD

**Issue by enochytchen** [mclements/rstpm2#27]
https://github.com/mclements/rstpm2/blob/f511b0002fa2c361ff4f19e54b5821291ec7f182/man/markov_msm.Rd#L386

Error in limits.and.aspect(default.prepanel, prepanel = prepanel, have.xlim = have.xlim,  : 
  need at least one panel
In addition: Warning message:
In plot.markov_msm(pred1, strata = ~nodes + size, xlab = "Years since surgery",  :
  More than one set of covariates; covariates have been standardised

https://github.com/mclements/rstpm2/blob/f511b0002fa2c361ff4f19e54b5821291ec7f182/man/markov_msm.Rd#L416
https://github.com/mclements/rstpm2/blob/f511b0002fa2c361ff4f19e54b5821291ec7f182/man/markov_msm.Rd#L417
https://github.com/mclements/rstpm2/blob/f511b0002fa2c361ff4f19e54b5821291ec7f182/man/markov_msm.Rd#L418
https://github.com/mclements/rstpm2/blob/f511b0002fa2c361ff4f19e54b5821291ec7f182/man/markov_msm.Rd#L419
https://github.com/mclements/rstpm2/blob/f511b0002fa2c361ff4f19e54b5821291ec7f182/man/markov_msm.Rd#L420

Warning message:
In plot.markov_msm(diffs, stacked = FALSE, ggplot2 = TRUE) :
  More than one set of covariates; covariates have been standardised

**Comment by mclements** [comment]
Enoch: thank you for this old bug report. I am not able to reproduce these warnings on the GitHub version -- so I believe that these issues have been addressed. Sincerely, Mark.
