### ISSUE TITLE
proposal to add lines.aft

### ISSUE THREAD

**Issue by heinztuechler** [mclements/rstpm2#30]
Dear Mark,

looking at rstpm2, I miss a lines-method for aft. It seems that it would essentially be plot.base.aft with setting add=TRUE.
Would the following addition to aft.R be reasonable?

lines.aft <-
          function(x,newdata=NULL,type="surv",
                   col=1,ci.col="grey",lty=par("lty"),
                   ci=FALSE,rug=FALSE,
                   var=NULL,exposed=NULL,times=NULL,
                   ...)
              plot.aft.base(x=x, newdata=newdata, type=type,
                            line.col=col, ci.col=ci.col, lty=lty,
                        add=TRUE,
                            ci=ci, rug=rug, var=var, exposed=exposed,
                            times=times, ...)
setMethod("lines", signature(x="aft"), lines.aft)

best regards,

Heinz

**Comment by mclements** [comment]
Heinz: belatedly, thank you! Can I include you as a co-author on the `rstpm2` package? If so, can you [email me](mailto:mark.clements@ki.se) your details, please? Sincerely, Mark.
