### ISSUE TITLE
Support for rstpm2 in marginaleffects

### ISSUE THREAD

**Issue by aghaynes** [mclements/rstpm2#33]
Hi Mark,

FYI, i requested the author of marginaleffects to include support for rstpm2 models in that package.

https://github.com/vincentarelbundock/marginaleffects/issues/1041

There seems to be a slight issue with SEs, but he seems optimistic that it can be supported.

**Comment by mclements** [comment]
@aghaynes : I have submitted a pull request. Let's continue the discussion at https://github.com/vincentarelbundock/marginaleffects/issues/1041. Sincerely, Mark.

**Comment by aghaynes** [comment]
That is great! Thanks so much, @mclements!

**Comment by mclements** [comment]
@aghaynes : did you have any other suggestions for how to improve `rstpm2`?

**Comment by aghaynes** [comment]
Not at the moment. A colleague has used it a lot more than me though. I'll ask if he has any suggestions and come back to you if he does :smile:

**Comment by aghaynes** [comment]
Here you go... :smile:

> If I remember correctly there is no standsurv command in rstpm2 (like this one in Stata: https://pclambert.net/software/standsurv/). With the integration in marginaleffects that might be partially covered but not completely. Standsurv can e.g. also be extended to include competing risks (https://pclambert.net/software/standsurv/standardized_cif/).

And maybe one from me... I would consider making a pkgdown site. They're so easy to make and everything can actually be handled through github actions after the initial setup.
